### ISSUE TITLE
aws-nuke should pause when the --force flag is enabled

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/aws-nuke#14]
To give users a chance to hit `CTRL+C` in case of error, aws-nuke should pause for 10 seconds with the log output "Pausing for 10 seconds to give you a last chance to hit CTRL+C" whenever the `--force` flag is enabled.

**Comment by tonerdo** [comment]
Fixed in #17

**Comment by tonerdo** [comment]
Fixed in #17
